### Event
POST http://localhost:5701/api/
Content-Type: application/json

{
  "Font": 1
}

### Manage
POST http://localhost:5701/api/manage
Content-Type: application/json

{
  "operation": "getLastDynamic",
  "data": {
    "uid": 387636363
  }
}

###获取直播间信息
GET https://api.live.bilibili.com/room/v1/Room/get_info?room_id=26088559

###获取用户动态
GET https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?offset=&host_mid=13874847&timezone_offset=-480

###获取用户信息
GET https://api.bilibili.com/x/relation/stat?vmid=387636363&jsonp=jsonp

###获取用户信息info
GET https://api.bilibili.com/x/web-interface/card?mid=387636363

###
GET https://api.bilibili.com/x/relation/followings?vmid=13874847&ps=100&pn=2